sudo: required

language: python

services:
    - docker

addons:
  ssh_known_hosts: gienah.uberspace.de

before_install:
    - docker pull jojomi/hugo

script:
- docker run -v $(pwd):/src -v /tmp/hugo-build:/output -t --rm jojomi/hugo

# Thanks to https://oncletom.io/2016/travis-ssh-deploy/
before_deploy:
- openssl aes-256-cbc -K $encrypted_caa7bf583e99_key -iv $encrypted_caa7bf583e99_iv -in deploy/deploy_rsa.enc -out /tmp/deploy_rsa -d
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/deploy_rsa
- ssh-add /tmp/deploy_rsa

deploy:
  provider: script
  skip_cleanup: true
  script: rsync -v --recursive --times --delete --prune-empty-dirs --filter='P .htaccess' --checksum /tmp/hugo-build gbprivat@gienah.uberspace.de:lebenplusplus-hugo/
#  on:
#    branch: master
