name: Build and deploy blog

# Run this workflow every time a new commit pushed to your repository
on: push

jobs:
  deploy:
    name: Deploy code to hosting provider
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      # Checks out a copy of your repository on the ubuntu-latest machine
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          submodules: true  # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.81.0'
          # extended: true

      - name: Build
        run: hugo --minify --theme blackburn --baseURL https://lebenplusplus.de/
        
      - name: rsync deployments
        uses: burnett01/rsync-deployments@4.1
        with:
          switches: -v --recursive --times --delete --prune-empty-dirs --filter='P .htaccess' --checksum
          path: public/
          remote_path: ${{ secrets.DEPLOY_TARGET_DIR }}
          remote_host: ${{ secrets.DEPLOY_HOST }}
          remote_user: ${{ secrets.DEPLOY_USER }}
          remote_key: ${{ secrets.DEPLOY_SSH }}  
