name: Super-Linter

# Run this workflow every time a new commit pushed to your repository
on: push

jobs:
  deploy:
    # Name the Job
    name: Deploy code to hosting provider
    # Set the type of machine to run on
    runs-on: ubuntu-latest

    steps:
      # Checks out a copy of your repository on the ubuntu-latest machine
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Build blog
        uses: jakejarvis/hugo-build-action@master  # ...or replace 'master' with a full version tag, such as: v0.64.1
        with:
          args: --minify --theme blackburn --baseURL https://lebenplusplus.de/
          
      - name: Create artifact
        uses: actions/upload-artifact@master
        with:
          name: website
          path: './public'
